services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    command: "-u '${NAS_USER};${NAS_PASSWORD}' -s 'public;/data;yes;no'"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "1445:445" # Revert to 445 if you don't need to access from Windows
    volumes:
      - ${STORAGE_BASE}/nas:/data
    networks:
      - lan_net

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - FB_USERNAME=${NAS_USER}
      - FB_PASSWORD=${NAS_PASSWORD}
    ports:
      - "18080:80"
    volumes:
      - ${STORAGE_BASE}/nas:/srv
    restart: always
    networks:
      - lan_net

networks:
  lan_net:
    external: true
