apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      initContainers:
      - name: init-config
        image: busybox:latest
        command: ['sh', '-c', 'cp /config-src/* /app/config/']
        volumeMounts:
        - name: homepage-config
          mountPath: /config-src
        - name: config
          mountPath: /app/config

      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config
          mountPath: /app/config
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: config
        emptyDir: {}
      - name: homepage-config
        configMap:
          name: homepage-config
