apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-downloads-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/media"
