services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    devices:
      - /dev/net/tun
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN=e9f2abfaaf4ab61f72d2f8730f63d4993ac7910064a3c398f0e069308d294260
      - CONNECT=Canada
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.50.0/24  # So it can be accessed within the local network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    networks:
      vpn_net:
        ipv4_address: 172.18.0.2
    restart: unless-stopped

networks:
  vpn_net:
    external: true


# services:
#   vpn:
#     image: ghcr.io/bubuntux/nordvpn
#     cap_add:
#       - NET_ADMIN               # Required
#       - NET_RAW                 # Required
#     environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
#       - TOKEN=mytoken
#       - CONNECT=Canada
#       - TECHNOLOGY=NordLynx
#       - NETWORK=192.168.50.0/24  # So it can be accessed within the local network
#     # ports:
#     #   - 8080:8080
#     sysctls:
#       - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
#     # networks:
#     #   - internal
#     restart: unless-stopped