services:
  qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrentvpn
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - VPN_PROV=custom
      - VPN_CLIENT=openvpn
      - LAN_NETWORK=${LAN_NETWORK}
      - NAME_SERVERS=1.1.1.1,8.8.8.8
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - DEBUG=false
    volumes:
      - ${STORAGE_BASE}/qbittorrent/appdata:/config
      - ${STORAGE_BASE}/nas/downloads:/data/downloads
      - ${STORAGE_BASE}/nas/torrents:/data/torrents
      - ${STORAGE_BASE}/qbittorrent/logs:/var/log/qbittorrent
      - ./vpn-config:/config/openvpn
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - lan_net
    restart: unless-stopped

networks:
  lan_net:
    external: true
