services:
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: torrent
    networks:
      vpn_net:
        ipv4_address: 172.18.0.10
      lan_net: {}
    dns:
      - 192.168.50.124
      # - 1.1.1.1
      # - 8.8.8.8
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./change-route.sh:/etc/cont-init.d/change-route.sh:ro
      - ${STORAGE_BASE}/qbittorrent/appdata:/config
      - ${STORAGE_BASE}/nas/downloads:/downloads #optional
    restart: unless-stopped

networks:
  vpn_net:
    external: true
  lan_net:
    external: true