[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/var/log/qbittorrent

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=/data/downloads
Session\DisableAutoTMMByDefault=false
Session\ExcludedFileNames=
Session\Interface=tun0
Session\InterfaceName=tun0
Session\Port=6881
Session\QueueingSystemEnabled=false
Session\SSL\Port=4588
Session\ShareLimitAction=Stop
Session\TempPath=/data/downloads/temp
Session\TempPathEnabled=true
Session\UseRandomPort=false

[Core]
AutoDeleteAddedTorrentFile=Never

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\Interface=tun0
Connection\InterfaceName=tun0
Connection\PortRangeMin=6881
Connection\UPnP=false
General\Locale=en
General\UseRandomPort=false
MailNotification\req_auth=true
WebUI\Address=*
WebUI\AuthSubnetWhitelist=192.168.50.0/24, 172.17.0.0/24, 172.18.0.0/24
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=false
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="PLACEHOLDER_WILL_BE_REPLACED_BY_SETUP_SCRIPT"
WebUI\ServerDomains=*
WebUI\UseUPnP=false

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
