[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/data/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=/data
Session\DisableAutoTMMByDefault=false
Session\ExcludedFileNames=
Session\Interface=tun0
Session\InterfaceName=tun0
Session\Port=6881
Session\QueueingSystemEnabled=false
Session\SSL\Port=4588
Session\ShareLimitAction=Stop
Session\TempPath=/data/temp
Session\TempPathEnabled=true
Session\UseRandomPort=false

[Core]
AutoDeleteAddedTorrentFile=Never

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\Interface=tun0
Connection\InterfaceName=tun0
Connection\PortRangeMin=6881
Connection\UPnP=false
General\Locale=en
General\UseRandomPort=false
MailNotification\req_auth=true
WebUI\Address=*
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\CSRFProtection=false
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="PLACEHOLDER_WILL_BE_REPLACED_BY_SETUP_SCRIPT"
WebUI\ServerDomains=*
WebUI\UseUPnP=false

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
