apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-defaults
  namespace: torrents
data:
  qBittorrent.conf: |
    [Application]
    FileLogger\Age=1
    FileLogger\AgeType=1
    FileLogger\Backup=true
    FileLogger\DeleteOld=true
    FileLogger\Enabled=true
    FileLogger\MaxSizeBytes=512000
    FileLogger\Path=/config/qBittorrent/logs

    [BitTorrent]
    Session\AddTorrentStopped=false
    Session\DefaultSavePath=/data/downloads
    Session\DisableAutoTMMByDefault=false
    Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
    Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
    Session\ExcludedFileNames=
    Session\Port=6881
    Session\QueueingSystemEnabled=false
    Session\SSL\Port=12688
    Session\ShareLimitAction=Stop
    Session\TempPath=/data/downloads/temp
    Session\TempPathEnabled=true

    [Core]
    AutoDeleteAddedTorrentFile=IfAdded

    [LegalNotice]
    Accepted=true

    [Meta]
    MigrationVersion=6

    [Network]
    Cookies=@Invalid()
    PortForwardingEnabled=false

    [Preferences]
    WebUI\Address=*
    WebUI\AlternativeUIEnabled=false
    WebUI\AuthSubnetWhitelist=10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\BanDuration=3600
    WebUI\CSRFProtection=true
    WebUI\ClickjackingProtection=true
    WebUI\CustomHTTPHeaders=
    WebUI\CustomHTTPHeadersEnabled=false
    WebUI\HTTPS\Enabled=false
    WebUI\HostHeaderValidation=true
    WebUI\LocalHostAuth=false
    WebUI\MaxAuthenticationFailCount=5
    WebUI\Password_PBKDF2="@ByteArray(RulusNN8N7A=:iEi3UR2z5OVd7dJlMEMNJGPndCyDGHmqq93c6hLpAKBXYcGOhGG0A+bhT89gMNJQvWbIw6OT6ck0Fn9IKC38aA==)"
    WebUI\Port=8080
    WebUI\ReverseProxySupportEnabled=false
    WebUI\SecureCookie=true
    WebUI\ServerDomains=*
    WebUI\SessionTimeout=3600
    WebUI\TrustedReverseProxiesList=
    WebUI\UseUPnP=true
    WebUI\Username=admin

  categories.json: |
    {
        "Movies": {
            "save_path": "__QBIT_MEDIA_ROOT__/movies"
        },
        "Music": {
            "save_path": "__QBIT_MEDIA_ROOT__/music"
        },
        "Shows": {
            "save_path": "__QBIT_MEDIA_ROOT__/tv"
        },
        "Games": {
            "save_path": "__QBIT_MEDIA_ROOT__/games"
        },
        "Books": {
            "save_path": "__QBIT_MEDIA_ROOT__/books"
        }
    }

  watched_folders.json: |
    {
        "/data/torrents": {
            "add_torrent_params": {
                "category": "",
                "content_layout": "Original",
                "download_limit": -1,
                "download_path": "",
                "operating_mode": "AutoManaged",
                "ratio_limit": -2,
                "save_path": "",
                "seeding_time_limit": -2,
                "skip_checking": false,
                "stopped": false,
                "upload_limit": -1,
                "use_auto_tmm": true,
                "use_download_path": false
            },
            "recursive": false
        }
    }
