apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-credentials
    namespace: nas
type: Opaque
stringData:
    FB_USERNAME: ENC[AES256_GCM,data:SKGr9rY=,iv:HLBU8F6VjGbk3pcyl0+oKYAQIahvzDjlJhi3M85TyYE=,tag:7GPHyjWobiqn8eaVsQ22bA==,type:str]
    FB_PASSWORD: ENC[AES256_GCM,data:qRYQ3Mh4zQMRvT+vdZY=,iv:0cq++lBS2q385FH+4B7LrWaJ+LpLQB8mAu4I6lbY94Y=,tag:Uk4xd5PTfnkaTCmjrX+CTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19m70lg0tsj5lrx55f8cr36re9kzh5gp8z3525flcpkm4d7zjf3gs8ggc5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVUFPZ1RkRmFJdk1wejd3
            V2ppT2k2SkluSDhkSTFOandYd0IwdXRaYkRjClRoYmdXcTdNZG0rK3d1NTUwNW96
            a0N2c2grTCtrcjFxcGc3aXpvT1lJQUUKLS0tIHR0Mk03NXZTazRuS25zVXZFZldF
            bVY1eWRNUWU3eHRFWThSbFNVN1pCR2MKoF9not0JMLDahINrPjrKMmmqkMaWE1rS
            l3fBiNXf/MPqiDM2juMP/jGSMCDi85ExtLNMbZeMAX+w1DUsQ+etxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T20:22:03Z"
    mac: ENC[AES256_GCM,data:lzZFu39gFCuFc/t5imdx9LEV6taKYI1Gq1Ty6YfbuMZbdI7jth57S+NrlmblvUqVZOykcLehV8vCZrnAA3hyaPLzfNc5dFOHACR8+Iz75AS2JZGLaZ+3eWJW1aR4n9RZ9oSV/OoQiS5myN8j5O1vE0NMG5dPRn2/uDu3nJPsCUU=,iv:Oba7r85Ii3+ShBSgChQtNakavchOtvK176042cRTHyU=,tag:N19BW6ClFcMPGG6KzTL+ZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
