apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-data
  namespace: management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName will be patched by environment overlay
