apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-media
  namespace: nas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  # storageClassName will be patched by environment overlays
